### ISSUE TITLE
NoMethodError in Account::Users#upload_avatar

### ISSUE THREAD

**Issue by MoyieRoller** [Langschwanzpinguine/Bahnhofottos#16]
Beim Klicken von "Upload picture" auf der settings page ohne neuen Avatar ausgewählt zu haben, entsteht ein Konflikt mit dem Länder Dropdown. Eigentlich sollte ein Popup kommen, das "no image selected anzeigt".

```
Showing .../Bahnhofottos/app/views/shared/_country_popup.html.erb where line #3 raised:

undefined method `each' for nil:NilClass

'.freeze;     @country_data.each do |region, countries| 
                           ^^^^^
```

**Comment by nils-matthaei** [comment]
Commit a1e62d7 should fix this. Closing issue.
