### ISSUE TITLE
feed: click on own profile pic returns "You are not friends with this user"

### ISSUE THREAD

**Issue by MoyieRoller** [Langschwanzpinguine/Bahnhofottos#21]

**Comment by nils-matthaei** [comment]
@JakobKohler fix this spaghetti code please 🍝

**Comment by MoyieRoller** [comment]
imagine we knew, who made the friendship model ^^

**Comment by nils-matthaei** [comment]
commit 2ef4ec9: Added redirect to profile page if user_id is the users own id
