### ISSUE TITLE
No images displayed in feed after redesign

### ISSUE THREAD

**Issue by nils-matthaei** [Langschwanzpinguine/Bahnhofottos#39]
The user has uploaded images but none are shown in the feed
![Screenshot 2024-08-08 at 22-42-51 Bahnhofottos](https://github.com/user-attachments/assets/34c62cb3-318b-451d-8886-ba27e711f0af)
![Screenshot 2024-08-08 at 22-42-40 Bahnhofottos](https://github.com/user-attachments/assets/d435a4aa-e3b7-41c9-bd5d-3ee043376128)

**Comment by MoyieRoller** [comment]
not sure, why this issue occurred... please have a look at your local instance, because: _works on my machine_

**Comment by MoyieRoller** [comment]
new test user accounts fixed the issue... no bug in code
