### ISSUE TITLE
Friendships sind verkehrt herum

### ISSUE THREAD

**Issue by nils-matthaei** [Langschwanzpinguine/Bahnhofottos#7]
Wenn man einen freund über `/users/friends` hinzufügt. Wird man selbst als ein Freund des  anderen users hinzugefügt. Lost as fuck.

**Comment by nils-matthaei** [comment]
Vielleicht machen wir das nochmal richtig from scratch

**Comment by JakobKohler** [comment]
Klingt komplett lost haha, F
